services:
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 80:80

  strapi:
    container_name: strapi
    build:
      context: ./strapi
      dockerfile: ./Dockerfile
    restart: always
    environment:
      - DATABASE_CLIENT=mysql
      - DATABASE_HOST=mariadb
      - DATABASE_PORT=3306
      - DATABASE_NAME=test
      - DATABASE_USERNAME=tester
      - DATABASE_PASSWORD=secret
      - APP_KEYS=random
      - API_TOKEN_SALT=random
      - ADMIN_JWT_SECRET=random
    volumes:
      - ./strapi/config:/srv/config
      - ./strapi/database:/srv/database
      - ./strapi/public:/srv/public
      - ./strapi/src:/srv/src
    ports:
      - 1337:1337

  mariadb:
    image: mariadb:10.7.4
    container_name: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=supersecret
      - MYSQL_DATABASE=test
      - MYSQL_USER=tester
      - MYSQL_PASSWORD=secret

volumes:
  data_db: